spring.data.mongodb.uri=mongodb+srv://resenalocompany_db_user:BKTexSELCeWrAJjY@cluster0.338au6w.mongodb.net/ResenaLO?appName=Cluster0&ssl=true&sslInvalidHostNameAllowed=true
spring.devtools.restart.enabled=true
app.s3.bucket=resenalo
app.s3.region=us-east-1
app.s3.prefix=images/